### ISSUE TITLE
Pushed branch.

### ISSUE THREAD

**Issue by MichaelTiernan** [chadmayfield/sysinfo#2]
I have *no* idea how my branch got pushed to your repo.
I'm sorry about that. I want that branch nuked.
I'll keep trying on my end but by all means, if you can, do so.
I'm sorry.

**Comment by MichaelTiernan** [comment]
I think I killed it. *IF* you see another push from me without a pull. Please accept my apologies and drop a bomb on it. :smiley: 

Thank you.

**Comment by chadmayfield** [comment]
Haha, I've been there, no worries! :)
